### ISSUE TITLE
How soon is soon?

### ISSUE THREAD

**Issue by bernhardmgruber** [kokkos/simd-math#36]
The README of this repository states:

> THIS IS A TEMPORARY DEVELOPMENT REPOSITORY. IT WILL BE MERGED INTO KOKKOS SOON.

And I have been watching the repository with great interest! But time has passed and it seems the activity has declined. Is an integration of the SIMD facilities here still on the roadmap for Kokkos? Or is there an alternative approach to SIMD planned for Kokkos?

Thanks a lot for your answer!

**Comment by dalg24** [comment]
Hi, it has been merged into Kokkos proper and will be released as part of Kokkos 3.7 (coming soon)

**Comment by bernhardmgruber** [comment]
That is great news, congratulations!

I found it here: https://github.com/kokkos/kokkos/tree/develop/simd

Thank you!
